backend:
  name: github
  repo: openknowledgebe/website

local_backend: true

media_folder: okbe-website/images/uploads
public_folder: /images/uploads

media_library:
  name: cloudinary
  config:
    cloud_name: dwyxk1pns
    api_key: 837367631382331
    use_transformations: true

collections:
  - name: 'activity'
    label: 'Activity'
    folder: 'content/activities'
    create: true
    identifier_field: name
    slug: '{{name}}'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Logo', name: 'logo', widget: 'image', allow_multiple: false }
      - { label: 'Color', name: 'color', widget: 'color', default: '#ffffff', allowInput: true }
      - { label: 'Pin', name: 'pin', widget: 'boolean' }
      - label: 'Tags'
        name: 'tags'
        widget: 'relation'
        multiple: true
        collection: settings
        file: tags
        value_field: tags.*.name
        search_fields: [tags.*.name]
        hint: Tag not found? Go to 'Settings > Tags' to add a new tag!
      - label: 'Activity page'
        name: 'activity_page'
        widget: 'list'
        max: 1
        hint: "Would you like to link to an existing page or create a new one? Choose accordingly (it's a 'one or the other' type of choice)!"
        types:
          - label: 'Link to existing page'
            name: 'existing_page'
            widget: object
            fields:
              - { label: 'URL', name: 'url', widget: string }
          - label: 'New page'
            name: 'new_page'
            widget: object
            fields:
              - label: 'Activity detail'
                name: 'detail'
                widget: 'object'
                collapsed: true
                summary: 'Expand'
                fields:
                  - { label: 'Catchphrase', name: 'catchphrase', widget: 'string', required: false }
                  - { label: 'Description', name: 'description', widget: 'markdown' }
                  - {
                      label: 'Featured Image',
                      name: 'featured_image',
                      widget: 'image',
                      allow_multiple: false,
                    }
                  - label: 'Contact info'
                    name: 'contact_info'
                    widget: object
                    fields:
                      - { label: Email, name: email, widget: string }
                      - { label: 'Website', name: 'website', widget: 'string', required: false }
                      - label: 'Socials'
                        required: false
                        name: 'socials'
                        widget: object
                        fields:
                          - { label: Github, name: github, widget: string, required: false }
                          - { label: 'Twitter', name: 'twitter', widget: 'string', required: false }
                          - { label: LinkedIn, name: linkedin, widget: string, required: false }
                          - {
                              label: 'Facebook',
                              name: 'facebook',
                              widget: 'string',
                              required: false,
                            }
                  - label: 'Members'
                    name: 'members'
                    widget: 'list'
                    allow_add: true
                    add_to_top: true
                    summary: '{{fields.name}}'
                    fields:
                      - { label: 'Name', name: 'name', widget: string }
                      - { label: 'Task', name: 'task', widget: 'string', required: false }
                      - label: 'Contact info'
                        name: 'contact_info'
                        widget: object
                        fields:
                          - { label: Email, name: email, widget: string }
                          - { label: 'Twitter', name: 'twitter', widget: 'string', required: false }
                          - { label: LinkedIn, name: linkedin, widget: string, required: false }
  - name: pages
    label: Pages
    files:
      - label: 'Team'
        name: team
        file: content/pages/team.md
        fields:
          - label: 'Board of directors'
            name: 'directors'
            widget: 'list'
            allow_add: true
            label_singular: 'a board member'
            summary: '{{fields.name}}'
            fields:
              - { label: 'Name', name: 'name', widget: string }
              - { label: 'Task', name: 'task', widget: 'string', required: false }
              - label: 'Contact info'
                name: 'contact_info'
                widget: object
                fields:
                  - { label: Email, name: email, widget: string }
                  - { label: 'Twitter', name: 'twitter', widget: 'string', required: false }
                  - { label: LinkedIn, name: linkedin, widget: string, required: false }
          - label: 'Team members'
            name: 'team'
            widget: 'list'
            allow_add: true
            label_singular: 'a member'
            summary: '{{fields.name}}'
            fields:
              - { label: 'Name', name: 'name', widget: string }
              - { label: 'Task', name: 'task', widget: 'string', required: false }
              - label: 'Contact info'
                name: 'contact_info'
                widget: object
                fields:
                  - { label: Email, name: email, widget: string }
                  - { label: 'Twitter', name: 'twitter', widget: 'string', required: false }
                  - { label: LinkedIn, name: linkedin, widget: string, required: false }
          - label: 'Open positions'
            name: 'positions'
            widget: 'list'
            allow_add: true
            label_singular: 'a position'
            summary: '{{fields.name}}'
            fields:
              - { label: 'Name', name: 'name', widget: string }
  - name: 'story'
    label: 'Story'
    folder: content/stories
    create: true
    slug: '{{title}}-{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}'
    fields:
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: string }
      - { label: 'Title', name: 'title', widget: string }
      - label: 'Post'
        name: 'post'
        widget: 'list'
        max: 1
        hint: "Is the post a tweet or would you like to create an article? Choose accordingly (it's a 'one or the other' type of choice)!"
        types:
          - label: 'Tweet'
            name: 'tweet'
            widget: object
            fields:
              - { label: 'URL', name: 'url', widget: string }
          - label: 'Article'
            name: 'article'
            widget: object
            fields:
              - { label: 'body', name: 'body', widget: markdown }
      - { label: 'Excerpt', name: 'excerpt', widget: text, required: false }
      - label: 'Tags'
        name: 'tags'
        widget: 'relation'
        multiple: true
        collection: settings
        file: tags
        value_field: tags.*.name
        search_fields: [tags.*.name]
        hint: Tag not found? Go to 'Settings > Tags' to add a new tag!
      - { label: 'Pin', name: 'pin', widget: boolean }
  - name: 'settings'
    label: 'Settings'
    files:
      - label: 'Tags'
        name: 'tags'
        file: content/tags.json
        format: json
        fields:
          - label: 'Tags'
            name: 'tags'
            widget: 'list'
            allow_add: true
            label_singular: 'a tag'
            summary: '{{fields.name}}'
            fields:
              - { label: 'Name', name: 'name', widget: string }
