backend:
  name: github
  repo: openknowledgebe/website

media_folder: static/img
public_folder: /img

collections:
  - name: 'activity'
    label: 'Activity'
    folder: 'content/activity'
    create: true
    identifier_field: name
    slug: '{{name}}'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Logo', name: 'logo', widget: 'image' }
