backend:
  name: github
  repo: openknowledgebe/website
  branch: main

local_backend: true

media_folder: static/images/uploads
public_folder: /images/uploads

publish_mode: editorial_workflow

collections:
  - name: 'activities'
    label: 'Activities'
    label_singular: 'Activity'
    folder: 'content/activities'
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    create: true
    identifier_field: name
    slug: '{{name}}'
    preview_path: 'activities/{{name}}'
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Logo', name: 'logo', widget: 'image', allow_multiple: false }
      - { label: 'Color', name: 'color', widget: 'color', default: '#ffffff', allowInput: true }
      - label: 'Tags'
        name: 'tags'
        widget: 'relation'
        multiple: true
        required: false
        collection: settings
        file: tags
        value_field: tags.*.name
        search_fields: [tags.*.name]
        hint: Tag not found? Go to 'Settings > Tags' to add a new tag!
      - { label: 'Website', name: 'to', widget: 'string', required: false }
      - { label: 'Catchphrase', name: 'catchphrase', widget: 'string', required: false }
      - { label: 'Description', name: 'body', widget: 'markdown' }
      - label: 'Featured image'
        name: 'featured_image'
        widget: 'object'
        fields:
          - { label: 'Image', name: 'image', widget: 'image', allow_multiple: false }
          - {
              label: 'Description',
              name: 'alt',
              widget: string,
              required: false,
              hint: 'a.k.a "ALT". Always fill this field if you can meaningfully describe the image.',
              default: '',
            }
      - label: 'Contact info'
        name: 'contact_info'
        widget: object
        fields:
          - { label: Email, name: email, widget: string }
          - label: 'Socials'
            required: false
            name: 'socials'
            widget: object
            fields:
              - { label: Github, name: github, widget: string, required: false }
              - { label: 'Twitter', name: 'twitter', widget: 'string', required: false }
              - { label: LinkedIn, name: linkedin, widget: string, required: false }
              - { label: 'Facebook', name: 'facebook', widget: 'string', required: false }
      - label: 'Members'
        name: 'members'
        widget: 'list'
        allow_add: true
        add_to_top: true
        summary: '{{fields.name}}'
        fields:
          - { label: 'Name', name: 'name', widget: string }
          - { label: 'Task', name: 'task', widget: 'string', required: false }
          - {
              label: 'Picture',
              name: 'picture',
              widget: 'image',
              allow_multiple: false,
              required: false,
            }
          - label: 'Contact info'
            name: 'contact_info'
            widget: object
            fields:
              - { label: Email, name: email, widget: string, required: false }
              - { label: 'Twitter', name: 'twitter', widget: 'string', required: false }
              - { label: LinkedIn, name: linkedin, widget: string, required: false }
  # - name: 'tweet_stories'
  #   label: 'Tweets'
  #   folder: content/stories/tweets
  #   label_singular: 'Tweet'
  #   create: true
  #   slug: '{{title}}-{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}'
  #   fields:
  #     - { label: 'Title', name: 'title', widget: string }
  #     - { label: 'URL', name: 'to', widget: string }
  #     - label: 'Tags'
  #       name: 'tags'
  #       widget: 'relation'
  #       multiple: true
  #       required: false
  #       collection: settings
  #       file: tags
  #       value_field: tags.*.name
  #       search_fields: [tags.*.name]
  #       hint: Tag not found? Go to 'Settings > Tags' to add a new tag!
  - name: 'stories'
    label: 'Stories'
    label_singular: 'Story'
    folder: content/stories
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    create: true
    slug: '{{year}}{{month}}{{day}}-{{title}}'
    preview_path: '{{year}}/{{month}}/{{day}}/{{title}}'
    fields:
      - label: 'Date'
        name: 'date'
        widget: 'datetime'
        picker_utc: true
        date_format: 'DD/MM/YYYY'
        time_format: false
        hint: "Format: 'DD/MM/YYYY'"
      - { label: 'Author', name: 'author', widget: string }
      - { label: 'Title', name: 'title', widget: string }
      - { label: 'Article', name: 'body', widget: markdown }
      - { label: 'Excerpt', name: 'excerpt', widget: text, required: false }
      - label: 'Tags'
        name: 'tags'
        widget: 'relation'
        multiple: true
        required: false
        collection: settings
        file: tags
        value_field: tags.*.name
        search_fields: [tags.*.name]
        hint: Tag not found? Go to 'Settings > Tags' to add a new tag!
  - name: pages
    label: Pages
    files:
      - label: 'Home'
        name: 'homepage'
        file: content/pages/home/index.md
        media_folder: ''
        public_folder: ''
        fields:
          - label: 'Header'
            name: 'header'
            widget: 'object'
            summary: 'Expand'
            collapsed: true
            fields:
              - { label: 'Tagline', name: 'tagline', widget: string }
              - { label: 'Mission', name: 'mission', widget: 'markdown', minimal: true }
              - label: 'Featured image'
                name: 'featured_image'
                widget: 'object'
                fields:
                  - { label: 'Image', name: 'image', widget: 'image', allow_multiple: false }
                  - {
                      label: 'Description',
                      name: 'alt',
                      widget: string,
                      required: false,
                      hint: 'a.k.a "ALT". Always fill this field if you can meaningfully describe the image.',
                      default: '',
                    }
              - label: 'Call to action'
                name: 'cta'
                widget: 'object'
                collapsed: true
                summary: 'Expand'
                fields:
                  - { label: 'Label', name: 'label', widget: 'string' }
                  - {
                      label: 'Link',
                      name: 'to',
                      widget: 'string',
                      hint: 'Use a relative URL (e.g. /about) if the link is an internal link. It is preferable to use a relative URL whenever possible!',
                    }
          - label: 'Activities Section'
            name: 'activities'
            widget: 'object'
            summary: 'Expand'
            collapsed: true
            fields:
              - label: 'Featured Activities'
                name: 'featured_activities'
                widget: 'list'
                max: 3
                allow_add: true
                add_to_top: true
                label_singular: 'an activity'
                summary: '{{field.activity}}'
                field:
                  {
                    label: 'Activity',
                    name: 'activity',
                    widget: 'relation',
                    collection: activities,
                    search_fields: ['name'],
                    value_field: '{{slug}}',
                    display_fields: ['name'],
                  }
              - label: 'Call to action'
                name: 'cta'
                widget: 'object'
                collapsed: true
                summary: 'Expand'
                fields:
                  - { label: 'Label', name: 'label', widget: 'string' }
                  - {
                      label: 'Link',
                      name: 'to',
                      widget: 'string',
                      hint: 'Use a relative URL (e.g. /about) if the link is an internal link. It is preferable to use a relative URL whenever possible!',
                    }
          - label: 'Stories Section'
            name: 'stories'
            widget: 'object'
            summary: 'Expand'
            collapsed: true
            fields:
              - label: 'Featured image'
                name: 'featured_image'
                widget: 'object'
                fields:
                  - { label: 'Image', name: 'image', widget: 'image', allow_multiple: false }
                  - {
                      label: 'Description',
                      name: 'alt',
                      widget: string,
                      required: false,
                      hint: 'a.k.a "ALT". Always fill this field if you can meaningfully describe the image.',
                      default: '',
                    }
              - label: 'Featured Stories'
                name: 'featured_stories'
                widget: 'list'
                max: 3
                allow_add: true
                add_to_top: true
                label_singular: 'a story'
                summary: '{{field.story}}'
                field:
                  {
                    label: 'Story',
                    name: 'story',
                    widget: 'relation',
                    collection: stories,
                    search_fields: ['title', 'date'],
                    value_field: '{{slug}}',
                    display_fields: ['title', 'date'],
                  }
              - label: 'Call to action'
                name: 'cta'
                widget: 'object'
                collapsed: true
                summary: 'Expand'
                fields:
                  - { label: 'Label', name: 'label', widget: 'string' }
                  - {
                      label: 'Link',
                      name: 'to',
                      widget: 'string',
                      hint: 'Use a relative URL (e.g. /about) if the link is an internal link. It is preferable to use a relative URL whenever possible!',
                    }
          - label: 'Newsletter Section'
            name: 'newsletter'
            widget: 'object'
            summary: 'Expand'
            collapsed: true
            fields:
              - { label: 'Heading', name: 'heading', widget: string }
              - { label: 'Subheading', name: 'subheading' }
          - label: 'SEO & Meta'
            name: 'seo'
            widget: 'object'
            fields:
              - {
                  label: 'Title',
                  name: 'title',
                  widget: 'string',
                  hint: 'Appears in the browser tab.',
                }
              - { label: 'Description', name: 'description', widget: 'string' }
      - label: 'Team'
        name: team
        file: content/pages/team/index.md
        media_folder: ''
        public_folder: ''
        fields:
          - label: 'Header'
            name: 'header'
            widget: object
            summary: Expand
            collapsed: true
            fields:
              - label: 'About volunteers'
                name: 'about_volunteers'
                widget: object
                summary: Expand
                collapsed: true
                fields:
                  - { label: 'Heading', name: 'heading', widget: 'string' }
                  - { label: 'Body', name: 'body', widget: markdown }
              - label: 'Featured image'
                name: 'featured_image'
                widget: 'object'
                fields:
                  - { label: 'Image', name: 'image', widget: 'image', allow_multiple: false }
                  - {
                      label: 'Description',
                      name: 'alt',
                      widget: string,
                      required: false,
                      hint: 'a.k.a "ALT". Always fill this field if you can meaningfully describe the image.',
                      default: '',
                    }
          - label: 'Team members'
            name: 'team'
            widget: 'list'
            allow_add: true
            add_to_top: true
            label_singular: 'a member'
            summary: '{{fields.name}}'
            fields:
              - { label: 'Name', name: 'name', widget: string }
              - { label: 'Task', name: 'task', widget: 'string', required: false }
              - {
                  label: 'Picture',
                  name: 'picture',
                  widget: 'image',
                  allow_multiple: false,
                  required: false,
                }
              - label: 'Contact info'
                name: 'contact_info'
                widget: object
                fields:
                  - { label: Email, name: email, widget: string }
                  - { label: 'Twitter', name: 'twitter', widget: 'string', required: false }
                  - { label: LinkedIn, name: linkedin, widget: string, required: false }
          - label: 'Board of directors'
            name: 'directors'
            widget: 'list'
            allow_add: true
            label_singular: 'a board member'
            add_to_top: true
            summary: '{{fields.name}}'
            fields:
              - { label: 'Name', name: 'name', widget: string }
              - { label: 'Task', name: 'task', widget: 'string', required: false }
              - {
                  label: 'Picture',
                  name: 'picture',
                  widget: 'image',
                  allow_multiple: false,
                  required: false,
                }
              - label: 'Contact info'
                name: 'contact_info'
                widget: object
                fields:
                  - { label: Email, name: email, widget: string }
                  - { label: 'Twitter', name: 'twitter', widget: 'string', required: false }
                  - { label: LinkedIn, name: linkedin, widget: string, required: false }
          - label: 'Open positions'
            name: 'positions'
            widget: 'object'
            summary: 'Expand'
            fields:
              - label: 'Employee'
                name: 'employee'
                widget: list
                add_to_top: true
                allow_add: true
                summary: '{{fields.job}}'
                field: { label: 'Job', name: 'job', widget: string }
              - label: 'Internship'
                name: 'internship'
                widget: list
                add_to_top: true
                allow_add: true
                summary: '{{fields.job}}'
                field: { label: 'Job', name: 'job', widget: string }
              - label: 'Volunteer'
                name: 'volunteer'
                widget: list
                add_to_top: true
                allow_add: true
                summary: '{{fields.job}}'
                field: { label: 'Job', name: 'job', widget: string }
          - label: 'SEO & Meta'
            name: 'seo'
            widget: 'object'
            fields:
              - {
                  label: 'Title',
                  name: 'title',
                  widget: 'string',
                  hint: 'Appears in the browser tab.',
                }
              - { label: 'Description', name: 'description', widget: 'string' }
      - label: 'About'
        name: 'about'
        file: content/pages/about/index.md
        media_folder: ''
        public_folder: ''
        fields:
          - { label: 'Content', name: 'body', widget: 'markdown' }
          - label: 'SEO & Meta'
            name: 'seo'
            widget: 'object'
            fields:
              - {
                  label: 'Title',
                  name: 'title',
                  widget: 'string',
                  hint: 'Appears in the browser tab.',
                }
              - { label: 'Description', name: 'description', widget: 'string' }
  - name: 'header_footer'
    label: 'Header & Footer'
    files:
      - label: 'Header'
        name: 'header'
        file: content/settings/header/index.md
        media_folder: ''
        public_folder: ''
        fields:
          - { label: 'Logo', name: 'logo', widget: 'image', allow_multiple: false }
          - { label: 'Organization Name', name: 'org_name', widget: string }
          - label: 'Menu Items'
            name: 'nav_items'
            widget: 'list'
            add_to_top: true
            fields:
              - { label: 'Label', name: 'label', widget: 'string' }
              - {
                  label: 'Link',
                  name: 'to',
                  widget: 'string',
                  hint: 'Use a relative URL (e.g. /about) if the link is an internal link. It is preferable to use a relative URL whenever possible!',
                }
      - label: 'Footer'
        name: 'footer'
        file: content/settings/footer/index.md
        fields:
          - label: 'Contact'
            name: 'contact'
            widget: 'object'
            summary: 'Expand'
            collapsed: true
            fields:
              - { label: 'Heading', name: 'heading', widget: string }
              - { label: 'Contact Info', name: 'contact_info', widget: markdown }
          - label: 'Socials'
            name: 'socials'
            widget: object
            summary: 'Expand'
            collapsed: true
            fields:
              - { label: 'Heading', name: 'heading', widget: string }
              - { label: Github, name: github, widget: string }
              - { label: 'Twitter', name: 'twitter', widget: 'string' }
              - { label: 'Facebook', name: 'facebook', widget: 'string' }
          - label: 'Footer Navigation'
            name: 'footer_nav'
            widget: 'list'
            fields:
              - { label: 'Label', name: 'label', widget: 'string' }
              - {
                  label: 'Link',
                  name: 'to',
                  widget: 'string',
                  hint: 'Use a relative URL (e.g. /about) if the link is an internal link. It is preferable to use a relative URL whenever possible!',
                }
          - label: 'Attributions'
            name: 'attributions'
            widget: 'markdown'
  - name: 'settings'
    label: 'Settings'
    files:
      - label: 'Tags'
        name: 'tags'
        file: content/settings/tags/index.json
        format: json
        fields:
          - label: 'Tags'
            name: 'tags'
            widget: 'list'
            allow_add: true
            add_to_top: true
            label_singular: 'a tag'
            summary: '{{fields.name}}'
            fields:
              - { label: 'Name', name: 'name', widget: string }
