export { default as Img } from './Img';
export { default as StyledLink } from './StyledLink';
export { default as Title } from './Title';
export { default as Tag } from './Tag';
export { default as Input } from './Input';
export { default as Button } from './Button';
export { default as Person } from './Person';
export { default as Date } from './Date';
export { default as Article } from './Article';
